version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./local.db
      - NEXTCLOUD_URL=${NEXTCLOUD_URL}
      - BODY_SIZE_LIMIT=1073741824
    labels:
      - "traefik.http.middlewares.limit.buffering.maxRequestBodyBytes=1073741824"
      - "traefik.http.middlewares.limit.buffering.maxResponseBodyBytes=1073741824"    
    volumes:
      - uploads_data:/app/uploads
      - db_data:/app
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:3000']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s  # Database management tool (only enable when needed)
  db-studio:
    build: .
    ports:
      - "4983:4983"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:./data/local.db
    volumes:
      - db_data:/app/data
    command: sh -c "pnpm install --include=dev && pnpm run db:studio --host 0.0.0.0"
    profiles:
      - debug
    restart: "no"

  adminer:
    image: adminer:4
    ports:
      - "8080:8080"
    volumes:
      - db_data:/var/www/html/uploads
    profiles:
      - debug
    restart: unless-stopped

volumes:
  uploads_data:
  db_data:
